export const SIDEBAR_COLOR = {
  SIDEBAR_BT_COLOR: '#349834',
  SIDEBAR_COLOR: '#252525',
  SIDEBAR_LN_COLOR: '#0f0',
  SIDEBAR_BT_COLOR_HOVER: '#0f0',
  SIDEBAR_TXT_COLOR: '#fff',
  SIDEBAR_ICON_COLOR: '#fff',
};